### ISSUE TITLE
Issue with Many-to-many association.

### ISSUE THREAD

**Issue by Nandanchaturvedi** [SAP-samples/cloud-cap-samples#93] opened 2020-06-03 15:10 UTC
I have created a many-to-many association as described here:
https://cap.cloud.sap/docs/guides/domain-models#managed-many-to-many-associations

However, while creating the entity, as it would be a deep insert, I get the following error:

**"message": "Error while deserializing payload. 'contacts' does not exist in type 'DSPPfgService.PfgRequests'."**

**Comment by Nandanchaturvedi** [comment] 2020-06-03 15:11
This is how i tried creating the entity   

{
            "ID": 1001,
            "title": "API Created",
            	"customer_ID":90002,
            	
            
            "contacts":[
				{
				"contact_ID" : 2
				},
				{
				"contact_ID" : 1
				}
			]
		}

**Comment by Nandanchaturvedi** [comment] 2020-06-12 00:33
While I try to make all IDs Guid, I get the following error:

{
    "error": {
        "code": "400",
        "message": "Deep insert with to-many Associations is not allowed"
    }
}



This is how the model looks like:

entity PfgRequests : managed, cuid {
  contacts                      :   Association to many PfgContacts on contacts.pfgRequest = $self;
}
entity Contacts : cuid {
  pfgRequests   : Association to many PfgContacts on pfgRequests.contact = $self;
}

entity PfgContacts {        //maintains many-many entity 
  key pfgRequest: Association to PfgRequests;
  key contact: Association to Contacts;
}

And I have exposed all three in the service

**Comment by chgeo** [comment] 2020-06-24 15:32
Seems to be duplicate of #94

**Closed by chgeo** 2020-06-24 15:32 UTC
