### ISSUE TITLE
UUID OData v2 adapter proxy

### ISSUE THREAD

**Issue by hmpbmp** [SAP-samples/cloud-cap-samples#96] opened 2020-06-08 15:02 UTC
Hello,

I have entity with UUID key (with @odata.type: string) that I provide in OData and I use v2 adapter to work with smart sapui5 controls. 
When I call entity set using v2 it works perfectly but when I call entity by key /Entity(guid'XXXXXXXXX') as it supposed to be by v2 standard, the adapter doesn't handle it. But removing 'guid' part works.

Can you please help with how I should define this key properly to work with v2 adapter?

Thank you,
Best Regards,
Semyon

**Comment by chgeo** [comment] 2020-06-24 15:31
@oklemenz or @oklemenz2 can you help here?

**Comment by oklemenz2** [comment] 2020-06-25 07:40
Hello Semyon, 

Can you try the latest version of CDS OData v2 Adapter Proxy 1.4.36: 
https://www.npmjs.com/package/@sap/cds-odata-v2-adapter-proxy

If the issue then still persists, I would need more information on your project.

`guid'05db01e5-28e6-4668-9fdb-7da666c2eec8'` is the correct way to pass a UUID in OData v2...
The CDS OData v2 Adapter Proxy then converts this to the UUID format in OData v2: 
05db01e5-28e6-4668-9fdb-7da666c2eec8.

Can you also check for warnings in the console, when activating logging by setting the env variable:
`XS_APP_LOG_LEVEL=debug`

Best regards, 

Oliver

**Comment by hmpbmp** [comment] 2020-06-25 16:45
Hello Oliver,

I've tried to install 1.4.36 version using `npm install @sap/cds-odata-v2-adapter-proxy@1.4.36` but it shows that no such version available. 
The best I managed to do is 1.4.33.

So I tried to access following URLs:
1) http://localhost:4004/TemplateContent/Templates('0a71e12e-03ff-4b7c-9985-44425dbba620') - v4, success
2) http://localhost:4004/v2/TemplateContent/Templates('0a71e12e-03ff-4b7c-9985-44425dbba620') - v2, success
3) http://localhost:4004/v2/TemplateContent/Templates(guid'0a71e12e-03ff-4b7c-9985-44425dbba620') - v2, error

As you mentioned previously using `guid` is correct way for v2 and metadata works the same but it seems that requests are handled differently.

Unfortunately, I currently have only local development so the best I could find in debug is following:
```
Jun 25, 2020 07:37:21 PM Request [kbv0f1xa] DEBUG: GET /v2/TemplateContent/Templates(guid'0a71e12e-03ff-4b7c-9985-44425dbba620')
Headers:
{"host":"localhost:4004","connection":"keep-alive","cache-control":"max-age=0","upgrade-insecure-requests":"1","user-agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.106 Safari/537.36","accept":"text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9","sec-fetch-site":"same-origin","sec-fetch-mode":"navigate","sec-fetch-user":"?1","sec-fetch-dest":"document","referer":"http://localhost:4004/v2/TemplateContent/Templates('0a71e12e-03ff-4b7c-9985-44425dbba620')","accept-encoding":"gzip, deflate, br","accept-language":"en,ru-RU;q=0.9,ru;q=0.8,sk;q=0.7","cookie":"remember_token=1|8d557347fed15c9ee4b4f88ad2f4336bcdd6e846d2c7874f7b1a5cd096f9d252347a19ff50d32f947c4f37f0349af5989b4e09bfcbe81875ebc9e75673972dee"}
Jun 25, 2020 07:37:21 PM Proxy Request [kbv0f1xa] DEBUG: GET /TemplateContent/Templates(0a71e12e-03ff-4b7c-9985-44425dbba620)
Headers:
{"host":"localhost:4004","connection":"keep-alive","cache-control":"max-age=0","upgrade-insecure-requests":"1","user-agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.106 Safari/537.36","accept":"text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9","sec-fetch-site":"same-origin","sec-fetch-mode":"navigate","sec-fetch-user":"?1","sec-fetch-dest":"document","referer":"http://localhost:4004/v2/TemplateContent/Templates('0a71e12e-03ff-4b7c-9985-44425dbba620')","accept-encoding":"gzip, deflate, br","accept-language":"en,ru-RU;q=0.9,ru;q=0.8,sk;q=0.7","cookie":"remember_token=1|8d557347fed15c9ee4b4f88ad2f4336bcdd6e846d2c7874f7b1a5cd096f9d252347a19ff50d32f947c4f37f0349af5989b4e09bfcbe81875ebc9e75673972dee","x-request-id":"kbv0f1xa","x-correlationid":"kbv0f1xa"}
GET /TemplateContent/Templates(0a71e12e-03ff-4b7c-9985-44425dbba620)
[2020-06-25T16:37:21.450Z | WARNING | 1070098]: Expected uri token 'ODataIdentifier' could not be found in 'Templates(0a71e12e-03ff-4b7c-9985-44425dbba620)' at position 11
Jun 25, 2020 07:37:21 PM Proxy Response [kbv0f1xa] DEBUG: 400 Bad Request
Headers:
{"x-powered-by":"Express","odata-version":"4.0","content-type":"application/xml","date":"Thu, 25 Jun 2020 16:37:21 GMT","connection":"close","content-length":"285"}
Body:
<?xml version="1.0" encoding="UTF-8"?><error xmlns="http://docs.oasis-open.org/odata/ns/metadata"><code>null</code><message>Expected uri token &apos;ODataIdentifier&apos; could not be found in &apos;Templates(0a71e12e-03ff-4b7c-9985-44425dbba620)&apos; at position 11</message></error>
Jun 25, 2020 07:37:21 PM Response [kbv0f1xa] DEBUG: 400 Bad Request
Headers:
{"x-powered-by":"Express","content-type":"application/xml","date":"Thu, 25 Jun 2020 16:37:21 GMT","connection":"close","content-length":285,"dataserviceversion":"2.0"}
Body:
<?xml version="1.0" encoding="UTF-8"?><error xmlns="http://docs.oasis-open.org/odata/ns/metadata"><code>null</code><message>Expected uri token &apos;ODataIdentifier&apos; could not be found in &apos;Templates(0a71e12e-03ff-4b7c-9985-44425dbba620)&apos; at position 11</message></error>
```
Thank you,
Best Regards,
Semyon

**Comment by oklemenz2** [comment] 2020-06-25 18:29
To use version 1.4.36 you have to set NPM registry to https://registry.npmjs.org/. But version 1.4.33 just also be ok.

That's really strange. I see in the logs, that the proxy request is correct:
```
/TemplateContent/Templates(0a71e12e-03ff-4b7c-9985-44425dbba620)
```

Strangely, you get the OData V4 error message 
```
Expected uri token 'ODataIdentifier' could not be found in 'Templates(0a71e12e-03ff-4b7c-9985-44425dbba620)'
```

When I try it on my side, this request works.

And even more strangely the v4 request, that you said work for as well
```
http://localhost:4004/TemplateContent/Templates('0a71e12e-03ff-4b7c-9985-44425dbba620') 
```
should not be valid. I get for this request the error messages:

```
Expected uri token 'ODataIdentifier' could not be found in 'Header('3c81a3f8-16db-4906-ba90-79fa435c24b7')' at position 8
```

So somethings very weird here.

Can you have a look which version of **@sap/cds** and **@sap/odata-server** you have in **node_modules**?

From my point of view, everything looks correct what the CDS OData v2 Adapter Proxy does, but the response of the CDS OData V4 service is somehow, the opposite of what it should be...
- UUID quoted: Shall return an error
- UUID not quoted: Shall be successful

Can you give more details on that? Do you have by chance your project available public somewhere?

**Comment by hmpbmp** [comment] 2020-06-26 07:52
Hello Oliver,

@sap/cds - 3.34.2
@sap/odata-server. - 1.7.1

I think that quotes are coming from the fact that we use GUID like this:
```
entity Templates : managed {
    key ID             : UUID @odata.Type : 'Edm.String';
...
```

Without the annotation, I managed to get behavior as you described.
I was following this part of documentation: [cap-uuids-odata](https://cap.cloud.sap/docs/guides/domain-models#mapping-uuids-to-odata) and it suggests to have this key as a string. 
What is the difference here in terms of how restrictive Edm.Guid is?

If we keep this annotation than why we have guid in metadata in the v2 version even when the key is identified as a string:
```
"d": {
"results": [
{
"ID": "0a71e12e-03ff-4b7c-9985-44425dbba620",
"version": 2,
"active_from": "/Date(1577836800000)/",
"is_active": false,
"is_new": false,
"typical_form_ID": "0ce304cc-5a70-44d6-8c7c-1d5cfcc63839",
"status_ID": "4493010e-b01c-4725-838e-dce41de7e3e9",
"warea_ID": "eaefad18-56dc-4f38-ae86-2a06b0e65e6a",
"createdByGroup_ID": "87c83ddc-0c6f-4ca3-b43d-2b040ee6d65a",
},
"status": {
"__deferred": {
"uri": "http://localhost:4004/v2/TemplateContent/Templates(guid'0a71e12e-03ff-4b7c-9985-44425dbba620')/status"
}
},
},
"__metadata": {
"uri": "http://localhost:4004/v2/TemplateContent/Templates(guid'0a71e12e-03ff-4b7c-9985-44425dbba620')",
"type": "sng.docbuilder.TemplateContent.Templates"
}
}
...
```
```
```

Thank you.

**Comment by oklemenz2** [comment] 2020-06-26 08:04
Thanks for your investigation.

From my point of view `@odata.Type : 'Edm.String'` is not needed for Node.js stack. As far as I remember this was introduced for the Java v2 stack, that made assumption of what a UUID is (Java has an own type UUID). In Node.js world, UUID is already a string, therefore I would prefer that the key is typed with UUID without `@odata.Type : 'Edm.String'.

Then you can use the notation as defined by OData v2 standard like this: guid'0a71e12e-03ff-4b7c-9985-44425dbba620'

If you overwrite the type in OData `@odata.Type : 'Edm.String', then basically the key is not a UUID anymore, but is interpreted as a string. And strings need to be quoted, as you already noticed, and should not be wrapped with `guid'..'`anymore...

So I see the two options:
1.) Omit `@odata.Type : 'Edm.String'`: Key needs to be specified as guid, by wrapping the key in `guid'...'`
2.) Use `@odata.Type : 'Edm.String'`: Key is a string and needs to be wrapped by single quotes without `guid`

In Node.js world, I clearly would prefer option 1.)

If you want to use Option 2, I think I need to do a fix on the CDS OData v2 Adapter Proxy, to respect the annotation `@odata.Type : 'Edm.String'` to render the uri in the result correctly without `guid''`...

I will provide a fix for that soon...

**Comment by oklemenz2** [comment] 2020-06-29 13:33
FYI: 
Version 1.4.37 of https://www.npmjs.com/package/@sap/cds-odata-v2-adapter-proxy now also supports: 
`@odata.Type : 'Edm.String'`, in case you would like to use it.

**Comment by chgeo** [comment] 2020-06-30 12:26
Closing, assuming the issue is addressed.

**Closed by chgeo** 2020-06-30 12:26 UTC
